[package]
name = "ic-management-types"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.2.1", default-features = false, features = [
    "compress-gzip",
    "macros",
] }
chrono = { version = "0.4.31", features = ["serde"] }
float-cmp = "0.9.0"
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
ic-nns-governance = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
ic-registry-subnet-type = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
ic-types = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
registry-canister = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
itertools = "0.11.0"
reqwest = { version = "0.11.9", features = ["json"] }
serde = "1.0.127"
serde_json = "1.0.66"
strum = "0.25.0"
strum_macros = "0.25.1"
url = "2.2.2"
anyhow = "1.0.43"
candid = "0.9.5"

[lib]
path = "src/lib.rs"
