[package]
name = "ic-management-types"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.2.1", default-features = false, features = [
    "compress-gzip",
    "macros",
] }
chrono = { version = "0.4.19", features = ["serde"] }
float-cmp = "0.9.0"
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "0062aec2efc16d6e4cadb2cd1052aaabbc9f6e48" }
ic-nns-governance = { git = "https://github.com/dfinity/ic.git", rev = "0062aec2efc16d6e4cadb2cd1052aaabbc9f6e48" }
ic-registry-subnet-type = { git = "https://github.com/dfinity/ic.git", rev = "0062aec2efc16d6e4cadb2cd1052aaabbc9f6e48" }
ic-types = { git = "https://github.com/dfinity/ic.git", rev = "0062aec2efc16d6e4cadb2cd1052aaabbc9f6e48" }
registry-canister = { git = "https://github.com/dfinity/ic.git", rev = "0062aec2efc16d6e4cadb2cd1052aaabbc9f6e48" }
itertools = "0.11.0"
reqwest = { version = "0.11.9", features = ["json"] }
serde = "1.0.127"
serde_json = "1.0.66"
strum = "0.25.0"
strum_macros = "0.25.1"
url = "2.2.2"
anyhow = "1.0.43"
candid = "0.8.4"

[lib]
path = "src/lib.rs"
