[package]
name = "ic-management-types"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "cfdbbf5fb5fdbc8f483dfd3a5f7f627b752d3156" }
serde_json = "1.0.66"
serde = "1.0.127"
strum = "0.24.1"
strum_macros = "0.24.3"
ic-types = { git = "https://github.com/dfinity/ic.git", rev = "cfdbbf5fb5fdbc8f483dfd3a5f7f627b752d3156" }
ic-registry-subnet-type = { git = "https://github.com/dfinity/ic.git", rev = "cfdbbf5fb5fdbc8f483dfd3a5f7f627b752d3156" }
ic-nns-governance = { git = "https://github.com/dfinity/ic.git", rev = "cfdbbf5fb5fdbc8f483dfd3a5f7f627b752d3156" }
serde_with = "2.0.1"
chrono = { version = "0.4.19", features = ["serde"] }
float-cmp = "0.9.0"
url = "2.2.2"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
