[package]
name = "ic-management-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
actix-web = { version = "4.2.1", default-features = false, features = [
    "compress-gzip",
    "macros",
] }
chrono = { version = "0.4.31", features = ["serde"] }
float-cmp = "0.9.0"
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-nns-governance = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-registry-subnet-type = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-types = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
registry-canister = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
itertools = "0.11.0"
reqwest = { version = "0.11.9", features = ["json"] }
serde = "1.0.127"
serde_json = "1.0.66"
strum = "0.25.0"
strum_macros = "0.25.1"
url = "2.2.2"
anyhow = "1.0.43"
candid = "0.9.5"
clap = { version = "4.4.10", features = ["derive"] }

[lib]
path = "src/lib.rs"
