[package]
name = "ic-management-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
actix-web = { workspace = true }
chrono = { workspace = true }
ic-base-types = { workspace = true }
ic-nns-governance = { workspace = true }
ic-registry-subnet-type = { workspace = true }
ic-types = { workspace = true }
registry-canister = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
url = { workspace = true }
anyhow = { workspace = true }
candid = { workspace = true }

[lib]
path = "src/lib.rs"
