[package]
name = "multiservice_discovery_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiservice_discovery_shared = { path = "../multiservice_discovery_shared" }
tokio = { workspace = true }
url = "2.2.2"
slog = { workspace = true }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
clap = { version = "4.3.0", features = ["derive"] }
humantime = "2.0"
ic-async-utils = { workspace = true }
futures-util = "0.3.5"
reqwest = { workspace = true }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
service-discovery = { path = "../service_discovery" }
regex = { workspace = true }
ic-types = { workspace = true }
