[package]
name = "config_writer_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { workspace = true }
service-discovery = { path = "../service_discovery" }
ic-types = { workspace = true }
slog = { workspace = true }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
serde = { workspace = true }
serde_json = { workspace = true }
ic-utils = { workspace = true }
erased-serde = "0.3.23"
serde_derive = "1.0.150"
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
url = { version = "2.1.1", features = ["serde"] }
