[package]
name = "dre"
build = "src/build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backon = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
candid = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap-num = { workspace = true }
colored = { workspace = true }
cycles-minting-canister = { workspace = true }
decentralization = { workspace = true }
dialoguer = { workspace = true }
dirs = { workspace = true }
dotenv = { workspace = true }
edit = { workspace = true }
flate2 = { workspace = true }
fs-err = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
shlex = { workspace = true }
ic-base-types = { workspace = true }
ic-canister-client = { workspace = true }
ic-canister-client-sender = { workspace = true }
ic-canisters = { workspace = true }
ic-interfaces-registry = { workspace = true }
ic-management-backend = { workspace = true }
ic-management-types = { workspace = true }
ic-nervous-system-clients = { workspace = true }
ic-nns-constants = { workspace = true }
ic-nervous-system-root = { workspace = true }
ic-nns-common = { workspace = true }
ic-nns-governance = { workspace = true }
ic-protobuf = { workspace = true }
ic-registry-keys = { workspace = true }
ic-registry-local-registry = { workspace = true }
ic-registry-subnet-type = { workspace = true }
ic-sns-wasm = { workspace = true }
ic-sys = { workspace = true }
ic-types = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
prost = { workspace = true }
regex = { workspace = true }
registry-canister = { workspace = true }
reqwest = { workspace = true }
self_update = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
socket2 = { workspace = true }
spinners = { workspace = true }
strum = { workspace = true }
tabled = { workspace = true }
tabular = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
humantime = { workspace = true }
clap_complete = "4.5.8"
cryptoki = { workspace = true }
keyring = { workspace = true }
comfy-table = { workspace = true }
wkhtmltopdf = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }

[build-dependencies]
clap = { workspace = true }
clap-num = { workspace = true }
ic-base-types = { workspace = true }
ic-management-types = { workspace = true }
url = { workspace = true }
ic-nns-governance = { workspace = true }
ic-registry-keys = { workspace = true }
humantime = { workspace = true }

[[bin]]
name = "dre"
path = "src/main.rs"

[lib]
name = "dre"
path = "src/lib.rs"
