[package]
name = "dre"
build = "build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
chrono = "0.4.31"
clap = { version = "4.2.7", features = [
    "derive",
    "env",
    "usage",
    "color",
    "help",
    "error-context",
    "suggestions",
    "wrap_help",
    "string",
    "cargo",
] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.68"
anyhow = "1.0.44"
futures = "0.3.21"
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.5.0"
regex = "1.5.4"
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-nns-constants = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-nns-governance = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-canister-client = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-sys = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-registry-nns-data-provider = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-registry-keys = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-registry-transport = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-protobuf = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-canisters = { path = "../ic-canisters" }
prost = "0.12.1"
tokio = { version = "1.14.0", features = ["full"] }
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = "0.25.1"
flate2 = "1.0.22"
dirs = "5.0.1"
decentralization = { path = "../decentralization" }
ic-management-types = { path = "../ic-management-types" }
ic-management-backend = { path = "../ic-management-backend" }
dialoguer = "0.10.0"
itertools = "0.11.0"
async-trait = "0.1.53"
keyring = "2.0.2"
cryptoki = "0.6.1"
candid = "0.9.5"
url = "2.3.1"
clap-num = "1.0.0"
sha2 = "0.10.6"
edit = "0.1.4"
tabular = "0.2"
ic-agent = "0.27.0"
actix-web = { version = "4.2.1", default-features = false, features = [
    "compress-gzip",
    "macros",
] }
dotenv = "0.15.0"
socket2 = "0.5.4"
spinners = "4.1.0"
tabled = "0.14.0"

[dev-dependencies]
tempfile = "3.3.0"
wiremock = "0.5.21"
