[package]
name = "np-notifications"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
ic-management-types = { path = "../ic-management-types" }
ic-management-backend = { path = "../ic-management-backend" }
ic-types = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
ic-registry-local-registry = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
slog-term = "2.9.0"
slog-async = "2.7.0"
tokio = { version = "1.29.1", features = ["full"] }
tokio-util = "0.7.8"
actix = "0.13.0"
url = "2.4.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde_json = "1.0.102"
serde = "1.0.171"
chrono = "0.4.26"
figment = { version = "0.10.10", features = ["env", "yaml"] }
ic-interfaces-registry = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
ic-registry-client-helpers = { git = "https://github.com/dfinity/ic.git", rev = "abac636d8a281a1e7600d876aaed10f7ce7e5040" }
serde_yaml = "0.9.25"
rand = "0.8.5"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = "0.3.17"
tracing-futures = { version = "0.2.5", features = ["tokio"] }

[dev-dependencies]
tempfile = "3.8.0"
pretty_assertions = "1.4.0"
