[package]
name = "np-notifications"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
ic-management-backend = { path = "../ic-management-backend" }
ic-management-types = { path = "../ic-management-types" }
ic-types = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7.8"
tracing = { version = "0.1.37", features = ["log"] }
tracing-log = { version = "0.2.0", features = ["log-tracer"] }
tracing-subscriber = "0.3.17"
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
pretty_assertions = "1.4.0"
httptest = "0.15.4"
# Default features disabled because it would require env_logger, and we are not using it
test-log = { version = "0.2.12", default-features = false, features = [
    "trace",
] }
# Necessary for test-log
# https://crates.io/crates/test-log
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
] }
