neurons: [
{
  key: 0
  value: {
    id: {
      id: 0
    }
    account: "\x9b\x6d\xce\x2c\x45\xa3\x5f\xfc\x65\x18\x6c\xf5\x61\x97\xfd\xfc\xae\x2d\x6d\x4a\x69\x6b\xa9\x16\x28\xdb\xff\x8f\xf6\xd8\xe9\x81"
    controller: {
      serialized_id: "\x72\xD6\x0B\x09\xA3\x10\xC3\x6E\x77\x96\x75\x91\x26\x70\xEF\x36\x9D\x47\x31\xB6\x36\xAC\x36\xCB\xE0\x37\x4B\x00\x02"
    }
    cached_neuron_stake_e8s: 1000000000
    aging_since_timestamp_seconds: 1611326356
    dissolve_delay_seconds: 252288000
    kyc_verified: true
    created_timestamp_seconds: 1611326356
    not_for_profit: false
    followees: [{
      key: 0
      value: { followees: [ {id: 49} ] }
    }]
  }
},{
  key: 49
  value: {
    id: {
      id: 0
    }
    account: "\x01\x02\x03\x04\x05\x06\x07\x08\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\x01\x02\x03\x04\x05\x06\x07\x08\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8"
    controller: {
      serialized_id: "\x5D\x73\x1A\x7D\x18\xEB\x54\x7C\x06\x0E\x6B\xB5\x56\x62\x18\x11\x19\x14\x98\x77\x73\x14\x60\x0E\xCF\x5A\xD9\xD8\x02"
    }
    cached_neuron_stake_e8s: 1000000000
    aging_since_timestamp_seconds: 1611326356
    dissolve_delay_seconds: 126144000
    kyc_verified: true
    created_timestamp_seconds: 1611326356
    not_for_profit: false
  }
},{
  key: 50
  value: {
    id: {
      id: 50
    }
    account: "\xfa\x23\x82\x3a\x6e\x97\xea\x91\x41\xd7\xf7\x87\x1a\xc6\xe9\xf1\xc4\x74\xf4\x98\xb9\xdc\x4a\x24\xe4\x9e\x14\x22\xa1\x77\x0a\x93"
    controller: {
      serialized_id: "\x29\x16\xBB\x33\xBE\xA3\x31\x04\x68\x82\x79\x6D\x3A\xB6\x80\x1E\x43\x94\x23\xD5\xC3\x6A\x1A\xF6\x3A\xA6\x05\x06\x02"
    }
    cached_neuron_stake_e8s: 1000000000
    aging_since_timestamp_seconds: 1611326356
    dissolve_delay_seconds: 126144000
    kyc_verified: true
    created_timestamp_seconds: 1611326356
    not_for_profit: false
    followees: [{
      key: 0
      value: { followees: [ {id: 49} ] }
    }]
  }
},{
  key: 449479075714955186
  value: {
    id: {
      id: 449479075714955186
    }
    account: "\x1d\x37\xb1\x77\x96\x70\xe5\x13\xc3\x0a\xbd\x80\x0f\xb1\xa4\x38\xa5\x6a\xa4\xa8\xb7\x74\xe7\x3f\x85\x22\xbc\xd9\x41\x97\xf1\x69"
    controller: {
      serialized_id: "\x04"
    }
    cached_neuron_stake_e8s: 1000000000
    aging_since_timestamp_seconds: 1611326356
    dissolve_delay_seconds: 126144000
    kyc_verified: true
    created_timestamp_seconds: 1611326356
    not_for_profit: false
    followees: [{
      key: 0
      value: { followees: [ {id: 49} ] }
    }]
  }
}
]
wait_for_quiet_threshold_seconds: 1209600 # two weeks
short_voting_period_seconds: 86400 # 24h
authz: {
  methods_authz: [{
    method_name: "submit_proposal"
    principal_ids: [
      "\x00\x00\x00\x00\x00\x00\x00\x03\x01\x01",
      "\x00\x00\x00\x00\x00\x00\x00\x04\x01\x01"
    ]
  }]
}
economics: {
  reject_cost_e8s: 100000000
  neuron_minimum_stake_e8s: 1000000000
  manage_neuron_cost_per_proposal_e8s: 1000000
  neuron_spawn_dissolve_delay_seconds: 1
  maximum_node_provider_rewards_e8s: 10000000000000
  transaction_fee_e8s: 137
}
genesis_timestamp_seconds: 1611326356
default_followees: [{
  key: 0
  value: { followees: [ {id: 49} ] }
}]

