default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: no-commit-to-branch
        stages: [commit]
  # The following repo is maintained by us at
  # https://gitlab.com/dfinity-lab/open/pre-commit-tools.
  - repo: https://gitlab.com/dfinity-lab/open/pre-commit-tools.git
    rev: 65e8990328b0651ab00d5653d26535d4080ca5f3
    hooks:
      - id: shfmt
        args: ["-w", "-i", "4", "-bn", "-ci"]
      - id: nixpkgs-fmt
        exclude: |
          (?x)^(
              .*/Cargo\.nix|
              experimental/.*
          )$
      - id: rustfmt
      - id: ormolu

  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
        exclude: |
          (?x)^(
              release-controller/release_index.py
          )$
        args:
          - --line-length=120

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        exclude: |
          (?x)^(
              release-controller/release_index.py
          )$
        args:
          - --application-directories=.:gitlab-ci/src/

  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: ["--config=flake8.cfg"]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        exclude: |
          (?x)^(
              release-controller/release_index.py
          )$
        args:
          - --ignore=D100,D103,D104,D203,D212
            # The default for pydocstyle is to match only on files that end in .py,
            # even if pre-commit specifies other files. This makes it so Python
            # files will be recognized regardless of extension.
          - --match=.*

  - repo: local
    hooks:
      - id: release-index-checks
        language: system
        name: release-index-checks
        verbose: true
        entry: |
          bash -c '
          files=("release-index-schema.json" "release-index.yaml" "release-controller/ci_check.py")

          found=false

          for file in "$@"; do
            if [[ "${files[@]}" =~ "$file" ]]; then
              found=true
              break
            fi
          done

          if [[ "$found" == false ]]; then
              exit 0
          fi
          command -v rye >/dev/null || echo 'rye' not found. Please install it by following the instructions from https://rye.astral.sh/
          rye run python release-controller/ci_check.py --repo-path ~/.cache/git/ic
          '
      - id: cargo-deny-checks
        language: system
        name: Cargo deny checks
        verbose: true
        entry: |
          bash -c '
          command -v cargo-deny >/dev/null || echo "'cargo-deny' not found. Please install it by running 'cargo install cargo-deny'"
          cargo deny check
          '
