site_name: DRE Documentation
site_description: Documentation for DFINITY's Decentralized Reliability Engineering (DRE) tools and processes
site_author: DFINITY Foundation

repo_name: dfinity/dre
repo_url: https://github.com/dfinity/dre/
edit_uri: edit/main/docs/

nav:
  - "Home": index.md
  - "Getting Started":
      - "Installation": getting-started.md
      - "Contributing Guide": contributing.md
      - "Documentation Guide": how-to-update-docs.md
  - "Core Concepts":
      - "Decentralization": decentralization.md
      - "Release Management": make-release.md
      - "Subnet Management": subnet-decentralization-whatif.md
      - "Trustworthy Metrics":
          - "Overview": trustworthy-metrics/trustworthy-metrics.md
          - "Architecture": trustworthy-metrics/architecture.md
          - "Untrusted Metrics": trustworthy-metrics/untrusted-metrics.md
  - "Guides":
      - "Creating a Neuron": create-a-neuron.md
      - "NNS Proposals": nns-proposals.md
      - "Submitting Motion Proposals": nns-motion-proposals.md
      - "Running Qualification": qualification/running-qualification.md
      - "Release Controller": release.md
      - "Being a DRE": be-dr-dre.md
  - "Development":
      - "Kubernetes":
          - "Tips and Tricks": k8s/tips-and-tricks.md
      - "Bazel":
          - "Tips and Tricks": bazel/tips-and-tricks.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - offline
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - git-committers:
      repository: dfinity/dre
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/katex.js
  - https://unpkg.com/katex@0.16/dist/katex.min.js
  - https://unpkg.com/katex@0.16/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0.16/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dfinity/dre
