[tool.poetry]
name = "release"
version = "0.1.0"
description = ""
authors = ["Release Team <eng-release@dfinity.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0,<4"
ansible = ">=7.0.0,<9.0.0"
colorama = "*"
elasticsearch = "<8.0,>=7.16"
elasticsearch-dsl = "*"
elasticsearch-follow = "*"
GitPython = "*"
numpy = "*"
pandas = "*"
paramiko = "*"
PyYAML = "*"
requests = "*"
tabulate = "*"
peewee = "*"
atlassian-python-api = "*"
python-dotenv = "*"
cachetools = "*"
pre-commit = "*"
pylint = "*"
tenacity = "*"
poetry = "^1.6.1"
ic-py = "*"


[tool.poetry.group.dev.dependencies]
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
