[tool.poetry]
name = "dre-repo"
version = "0.2.0"
description = ""
authors = ["DRE Team <dept-DRE@dfinity.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0,<4"
ansible = ">=7.0.0,<10.0.0"
colorama = "*"
elasticsearch = "<8.0,>=7.16"
elasticsearch-dsl = "*"
elasticsearch-follow = "*"
GitPython = "*"
numpy = "*"
pandas = "*"
paramiko = "*"
PyYAML = "*"
requests = "*"
tabulate = "*"
peewee = "*"
atlassian-python-api = "*"
python-dotenv = "*"
cachetools = "*"
pre-commit = "*"
pylint = "*"
tenacity = "*"
poetry = "^1.8.2"
ic-py = "*"
mkdocs-material = "^9.5.18"
mkdocs = "^1.5.3"
clickhouse-connect = "^0.7.8"
humanfriendly = "^10.0"
jupyter = "^1.0.0"
matplotlib = "^3.8.4"
ipython = "^8.24.0"
mkdocs-git-revision-date-localized-plugin = "^1.2.4"
mkdocs-git-committers-plugin-2 = "^2.2.3"
pydiscourse = "^1.7.0"
datamodel-code-generator = "^0.25.6"
pydantic-yaml = "^1.2.1"
google-api-python-client = "^2.127.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.0"
pydrive2 = "^1.19.0"
markdownify = "^0.12.1"
pytest = "^8.2.0"
pygithub = "^2.2.0"
pytest-mock = "^3.12.0"
mammoth = "^1.7.0"
slack-sdk = "^3.27.1"
git-changelog = "^2.5.2"
wrapt = "1.16.0"


[tool.poetry.group.dev.dependencies]
black = "^24"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
