[tool.poetry]
name = "dre-repo"
version = "0.2.0"
description = ""
authors = ["DRE Team <dept-DRE@dfinity.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0,<4"
ansible = ">=7.0.0,<10.0.0"
colorama = "*"
elasticsearch = "<8.0,>=7.16"
elasticsearch-dsl = "*"
elasticsearch-follow = "*"
GitPython = "*"
numpy = "*"
pandas = "*"
paramiko = "*"
PyYAML = "*"
requests = "*"
tabulate = "*"
peewee = "*"
atlassian-python-api = "*"
python-dotenv = "*"
cachetools = "*"
pre-commit = "*"
pylint = "*"
tenacity = "*"
poetry = "^1.6.1"
ic-py = "*"
mkdocs-material = "^9.5.9"
mkdocs = "^1.5.3"
clickhouse-connect = "^0.7.0"
humanfriendly = "^10.0"
jupyter = "^1.0.0"
matplotlib = "^3.8.2"
ipython = "^8.21.0"
mkdocs-git-revision-date-localized-plugin = "^1.2.4"
mkdocs-git-committers-plugin-2 = "^2.2.3"


[tool.poetry.group.dev.dependencies]
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
