# This inventory file can be used together with other testnet inventory files,
# in order to reduce config/code duplication between inventory files.
# This is in line with the DRY principle
# https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
#
# Example use:
# ansible-playbook -i env/${network}/hosts,env/shared

prometheus:
  vars:
    stage: all
    hosts: prometheus.dfinity.systems

data_centers:
  an1:
    vars:
      ipv6_prefix: "2001:920:401a:1708"
      ipv6_subnet: "/64"
  at1:
    vars:
      ipv6_prefix: "2607:f758:1220:0"
      ipv6_subnet: "/64"
  at2:
    vars:
      ipv6_prefix: "2604:3fc0:2001:0"
      ipv6_subnet: "/64"
  aw1:
    vars:
      ipv6_prefix: "2604:7e00:30:3"
      ipv6_subnet: "/64"
  bc1:
    vars:
      ipv6_prefix: "2001:438:fffd:11c"
      ipv6_subnet: "/64"
  bo1:
    vars:
      ipv6_prefix: "2600:c0d:3002:4"
      ipv6_subnet: "/64"
  br1:
    vars:
      ipv6_prefix: "2001:920:401a:1710"
      ipv6_subnet: "/64"
  br2:
    vars:
      ipv6_prefix: "2001:920:401a:1706"
      ipv6_subnet: "/64"
  bu1:
    vars:
      ipv6_prefix: "2a04:9dc0:0:108"
      ipv6_subnet: "/64"
  ch1:
    vars:
      ipv6_prefix: "2607:f6f0:3004:1"
      ipv6_subnet: "/64"
  ch2:
    vars:
      ipv6_prefix: "2604:7e00:50:0"
      ipv6_subnet: "/64"
  ch3:
    vars:
      ipv6_prefix: "2607:ff70:3:2"
      ipv6_subnet: "/64"
  dl1:
    vars:
      ipv6_prefix: "2600:3000:6100:200"
      ipv6_subnet: "/64"
  dm1:
    vars:
      ipv6_prefix: "2604:6800:258:1"
      ipv6_subnet: "/64"
  fm1:
    vars:
      ipv6_prefix: "2001:470:1:c76"
      ipv6_subnet: "/64"
  fr1:
    vars:
      ipv6_prefix: "2001:4d78:40d:0"
      ipv6_subnet: "/64"
  fr2:
    vars:
      ipv6_prefix: "2001:4d78:400:10a"
      ipv6_subnet: "/64"
  ge1:
    vars:
      ipv6_prefix: "2a0f:cd00:2:1"
      ipv6_subnet: "/64"
  ge2:
    vars:
      ipv6_prefix: "2a00:fa0:3:0"
      ipv6_subnet: "/64"
  hu1:
    vars:
      ipv6_prefix: "2604:b900:4001:76"
      ipv6_subnet: "/64"
  jv1:
    vars:
      ipv6_prefix: "2600:2c01:21:0"
      ipv6_subnet: "/64"
  lj1:
    vars:
      ipv6_prefix: "2a02:800:2:2003"
      ipv6_subnet: "/64"
  ln1:
    vars:
      ipv6_prefix: "2a0b:21c0:4003:2"
      ipv6_subnet: "/64"
  lv1:
    vars:
      ipv6_prefix: "2600:3006:1400:1500"
      ipv6_subnet: "/64"
  mb1:
    vars:
      ipv6_prefix: "2a00:fc0:5000:300"
      ipv6_subnet: "/64"
  mm1:
    vars:
      ipv6_prefix: "2001:1900:2100:2827"
      ipv6_subnet: "/64"
  mr1:
    vars:
      ipv6_prefix: "2a0b:21c0:b002:2"
      ipv6_subnet: "/64"
  mu1:
    vars:
      ipv6_prefix: "2a01:138:900a:0"
      ipv6_subnet: "/64"
  ny1:
    vars:
      ipv6_prefix: "2607:f1d0:10:1"
      ipv6_subnet: "/64"
  or1:
    vars:
      ipv6_prefix: "2604:3fc0:3002:0"
      ipv6_subnet: "/64"
  ph1:
    vars:
      ipv6_prefix: "2610:190:6000:1"
      ipv6_subnet: "/64"
  pl1:
    vars:
      ipv6_prefix: "2600:3004:1200:1200"
      ipv6_subnet: "/64"
  se1:
    vars:
      ipv6_prefix: "2600:c00:2:100"
      ipv6_subnet: "/64"
  sf1-old:
    vars:
      ipv6_prefix: "2607:fb58:9005:42"
      ipv6_subnet: "/64"
  sf1:
    vars:
      ipv6_prefix: "2602:fb2b:100:10::1"
      ipv6_subnet: "/64"
  sh1:
    vars:
      ipv6_prefix: "2001:4c08:2003:b09"
      ipv6_subnet: "/64"
  sg1:
    vars:
      ipv6_prefix: "2401:3f00:1000:24"
      ipv6_subnet: "/64"
  sg2:
    vars:
      ipv6_prefix: "2401:3f00:1000:22"
      ipv6_subnet: "/64"
  sg3:
    vars:
      ipv6_prefix: "2401:3f00:1000:23"
      ipv6_subnet: "/64"
  sj1:
    vars:
      ipv6_prefix: "2600:c02:b002:15"
      ipv6_subnet: "/64"
  sj2:
    vars:
      ipv6_prefix: "2001:438:fffd:4a"
      ipv6_subnet: "/64"
  st1:
    vars:
      ipv6_prefix: "2610:190:df01:5"
      ipv6_subnet: "/64"
  to2:
    vars:
      ipv6_prefix: "2001:438:8000:10"
      ipv6_subnet: "/64"
  tp1:
    vars:
      ipv6_prefix: "2607:f758:c300:0"
      ipv6_subnet: "/64"
  ty1:
    vars:
      ipv6_prefix: "2602:ffe4:801:16"
      ipv6_subnet: "/64"
  ty2:
    vars:
      ipv6_prefix: "2602:ffe4:801:17"
      ipv6_subnet: "/64"
  ty3:
    vars:
      ipv6_prefix: "2602:ffe4:801:18"
      ipv6_subnet: "/64"
  zh1:
    vars:
      ipv6_prefix: "2a00:fb01:400:42"
      ipv6_subnet: "/64"
  zh2:
    vars:
      ipv6_prefix: "2a00:fb01:400:200"
      ipv6_subnet: "/64"
  zh3:
    vars:
      ipv6_prefix: "2a02:418:3002:0"
      ipv6_subnet: "/64"
  zh4:
    vars:
      ipv6_prefix: "2a02:41b:300e:0"
      ipv6_subnet: "/64"
  zh5:
    vars:
      ipv6_prefix: "2a01:2a8:a13d:1"
      ipv6_subnet: "/64"
  zh6:
    vars:
      ipv6_prefix: "2a01:2a8:a13c:1"
      ipv6_subnet: "/64"
  zh7:
    vars:
      ipv6_prefix: "2a01:2a8:a13e:1"
      ipv6_subnet: "/64"
  zh8:
    vars:
      ipv6_prefix: "2a00:fb01:400:200"
      ipv6_subnet: "/64"
# Boundary network
  am6:
    vars:
      ipv6_prefix: "2604:1380:4601:6200"
      ipv6_subnet: "/64"
  am6-bnd00:
    vars:
      ipv6_prefix: "2604:1380:4601:6201"
      ipv6_subnet: "/64"
  am6-bns00:
    vars:
      ipv6_prefix: "2604:1380:4601:6202"
      ipv6_subnet: "/64"
  bo1-bnp00:
    vars:
      ipv6_prefix: "2600:c0d:3002:4"
      ipv6_subnet: "/64"
  da11:
    vars:
      ipv6_prefix: "2604:1380:4641:6100"
      ipv6_subnet: "/64"
  da11-bnd00:
    vars:
      ipv6_prefix: "2604:1380:4641:6101"
      ipv6_subnet: "/64"
  dm1-bnp00:
    vars:
      ipv6_prefix: "2604:6800:258:1"
      ipv6_subnet: "/64"
  ln1-bnp00:
    vars:
      ipv6_prefix: "2a0b:21c0:4003:2"
      ipv6_subnet: "/64"
  mr1-bnp00:
    vars:
      ipv6_prefix: "2a0b:21c0:b002:2"
      ipv6_subnet: "/64"
  se1-bnp00:
    vars:
      ipv6_prefix: "2600:c00:2:100"
      ipv6_subnet: "/64"
  sh1-bnp00:
    vars:
      ipv6_prefix: "2001:4c08:2003:b09"
      ipv6_subnet: "/64"
  sg1-bnp00:
    vars:
      ipv6_prefix: "2604:1380:40e1:4701"
      ipv6_subnet: "/64"
  sg1-bnp01:
    vars:
      ipv6_prefix: "2604:1380:40e1:4702"
      ipv6_subnet: "/64"
  sg1-bnp01:
    vars:
      ipv6_prefix: "2604:1380:40e1:4702"
      ipv6_subnet: "/64"
  sv15:
    vars:
      ipv6_prefix: "2604:1380:45e1:a600"
      ipv6_subnet: "/64"
  sv15-bnd00:
    vars:
      ipv6_prefix: "2604:1380:45e1:a601"
      ipv6_subnet: "/64"
  sv15-bnp00:
    vars:
      ipv6_prefix: "2604:1380:45e1:a603"
      ipv6_subnet: "/64"
  sv15-bnp01:
    vars:
      ipv6_prefix: "2604:1380:45e1:a604"
      ipv6_subnet: "/64"
  zh2-bnp00:
    vars:
      ipv6_prefix: "2a00:fb01:400:200"
      ipv6_subnet: "/64"
  zh2-bnp01:
    vars:
      ipv6_prefix: "2a00:fb01:400:200"
      ipv6_subnet: "/64"

physical_hosts:
  vars:
    become_method: sudo

nodes:
  vars:
    ansible_user: admin
    become_user: root
    become_method: sudo
    p2p_listen_port: 4100
    p2p_listen_ip: "{{ ipv6_address }}"
    p2p_listen_addr: "[{{ p2p_listen_ip }}]:{{ p2p_listen_port }}"

    xnet_listen_port: 2497
    xnet_listen_ip: "{{ ipv6_address }}"
    xnet_listen_addr: "[{{ xnet_listen_ip }}]:{{ xnet_listen_port }}"

    api_listen_port: 8080
    api_listen_ip: "{{ ipv6_address }}"
    api_listen_addr: "[{{ api_listen_ip }}]:{{ api_listen_port }}"
    api_listen_protocol: http
    api_listen_url: "{{ api_listen_protocol }}://{{ api_listen_addr }}"

    metrics_listen_port: 9090
    metrics_listen_ip: "{{ ipv6_address }}"
    metrics_listen_addr: "[{{ metrics_listen_ip }}]:{{ metrics_listen_port }}"

    node_exporter_metrics_listen_ip: "{{ ipv6_address }}"
    node_exporter_metrics_listen_port: 9100
    node_exporter_metrics_listen_addr: "[{{ node_exporter_metrics_listen_ip }}]:{{ node_exporter_metrics_listen_port }}"

    orchestrator_metrics_listen_ip: "{{ ipv6_address }}"
    orchestrator_metrics_listen_port: 9091
    orchestrator_metrics_listen_addr: "[{{ orchestrator_metrics_listen_ip }}]:{{ orchestrator_metrics_listen_port }}"

    journalbeat_hosts:
      - "elasticsearch-node-0.mercury.dfinity.systems:443"
      - "elasticsearch-node-1.mercury.dfinity.systems:443"
      - "elasticsearch-node-2.mercury.dfinity.systems:443"
      - "elasticsearch-node-3.mercury.dfinity.systems:443"

boundary:
  vars:
    api_listen_port: 443
    api_listen_protocol: https
    elasticsearch_url: "https://elasticsearch.mercury.dfinity.systems"
    ipv6_debug_ips:
      - "2001:4d78:40d::/48"  # FR1
      - "2607:f6f0:3004::/48" # CH1
      - "2607:fb58:9005::/48" # SF1-old
      - "2602:fb2b:100::/48"  # SF1
      - "2a00:fb01:400::/56"  # ZH1
    ipv6_monitoring_ips:
      - "2a05:d01c:e2c:a700::/56" # AWS eu-west-2 London Monitoring VPC
      - "2a05:d01c:d9:2b00::/56" # prometheus.mainnet.dfinity.network

all:
  vars:
    ansible_python_interpreter: python3
    become_method: sudo
