[package]
name = "qualifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
ic-nervous-system-common-test-keys = { workspace = true }
dirs = { workspace = true }
dre = { path = "../cli" }
ic-management-types = { path = "../ic-management-types" }
ic-canisters = { path = "../ic-canisters" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
ic-management-backend = { path = "../ic-management-backend" }
backon = { workspace = true }
chrono.workspace = true
indexmap.workspace = true
strum.workspace = true
futures.workspace = true
