#!/bin/bash
set -eEuo pipefail

# Clippy arguments copied from the ones used in the IC repo
cargo clippy --locked --all-features --tests --benches -- \
    -D warnings -D clippy::all -D clippy::mem_forget \
    -A clippy::redundant_closure -A clippy::too_many_arguments \
    -C debug-assertions=off
