[package]
name = "obs-canister-clients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-agent = { version = "0.30.2", features = ["hyper"] }
candid = { version = "0.9.10", features = ["parser"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
url = "2.2.2"
slog = { version = "2.7.0", features = [
  "max_level_trace",
  "nested-values",
  "release_max_level_debug",
  "release_max_level_trace",
] }