[package]
name = "obs-canister-clients"
version = { workspace = true }
edition = { workspace = true }
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-agent = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
