[package]
name = "vector_config_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
clap = { version = "4.3.0", features = ["derive"] }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
futures-util = "0.3.5"
humantime = "2.0"
ic-async-utils = { workspace = true }
ic-metrics = { workspace = true }
ic-types = { workspace = true }
ic-utils = { workspace = true }
ic-registry-local-registry = { workspace = true }
ic-interfaces-registry = { workspace = true }
ic-registry-nns-data-provider = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
service-discovery = { path = "../service_discovery" }
slog = { workspace = true }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tokio = { workspace = true }
url = { version = "2.1.1", features = ["serde"] }
config_writer_common = { path = "../config_writer_common" }
ic-http-endpoints-metrics = { workspace = true }
ic-config = { workspace = true }

[[bin]]
name = "vector_config_generator"
path = "src/main.rs"
