[package]
name = "multiservice-discovery"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
crossbeam-channel = { workspace = true }
erased-serde = { workspace = true }
futures-util = { workspace = true }
humantime = { workspace = true }
ic-async-utils = { workspace = true }
ic-crypto-utils-threshold-sig-der = { workspace = true }
ic-registry-client = { workspace = true }
ic-management-types = { workspace = true }
ic-types = { workspace = true }
ic-utils = { workspace = true }
multiservice-discovery-shared = { path = "../multiservice-discovery-shared" }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
service-discovery = { path = "../service-discovery" }
slog = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
warp = { workspace = true }
futures.workspace = true

[dev-dependencies]
tempdir = "0.3.7"
reqwest = "0.11.23"
assert_cmd = "2.0.13"
anyhow = "1.0.79"
