[package]
name = "multiservice-discovery"
version = { workspace = true }
edition = { workspace = true }
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
humantime = { workspace = true }
ic-async-utils = { workspace = true }
ic-crypto-utils-threshold-sig-der = { workspace = true }
ic-registry-client = { workspace = true }
ic-management-types = { workspace = true }
ic-types = { workspace = true }
multiservice-discovery-shared = { path = "../multiservice-discovery-shared" }
serde = { workspace = true }
serde_json = { workspace = true }
service-discovery = { path = "../service-discovery" }
slog = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
futures.workspace = true
axum = { workspace = true }
axum-otel-metrics.workspace = true
opentelemetry.workspace = true
retry = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
reqwest = { workspace = true }
assert_cmd = "2.0.16"
anyhow = "1.0.86"
flate2 = "1.0.33"
