#!/usr/bin/env bash
# When deploying, a dedicated release branch is created.  Changes committed there will not be made to a working branch you may have been on previously.
# This forcefully sets that other branch to be like this one.
set -eux
working_branch="${1}"
git stash
branch="$(git rev-parse --abbrev-ref HEAD)"
git checkout "$working_branch"
git reset --hard "$branch"
git push
git checkout "$branch"
echo "You may wish to pop uncommitted changes"
