#!/usr/bin/env bash
# Print the current step, and its parents for context.
#
# If the current step is 3.C.1 this will print:
# # 3 Description of step 3
# ## 3.C Description of step 3.C
# ### 3.C1 Description of step 3.C.1

TMPDIR="$HOME/tmp"
export TMPDIR

if (($# == 0)); then
    # Print where we are in the execution hierarchy.
    tail -n 1 "$TMPDIR/bootstrap/step_log" \
        | while read line; do
            echo "$line"
            line="$(echo "$line" | awk '{print $1}')"
            for ((count = 0; count < 10; count++)); do
                [[ "${line:-}" != "" ]] || break
                grep -E "^step $line " ../bootstrap.sh
                line="$(echo "$line" | sed -E 's/([.]|^)[^.]*$//g')"
            done
        done | tac
    echo "Date now:" "$(date -u --rfc-3339=seconds)"
else
    # Print the last N steps that we executed.
    tail -n "${1:-1}" "$TMPDIR/bootstrap/step_log"
fi
