[package]
name = "node-provider-rewards-api"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ic-base-types = { workspace = true }
rust_decimal = { workspace = true }
rewards-calculation-deprecated = { workspace = true }
rewards-calculation = { workspace = true }
ic-node-rewards-canister-protobuf = { workspace = true }
ic-nervous-system-proto = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
chrono = { version = "0.4.41", default-features = false, features = [
    "alloc",
    "serde",
] }

[lib]
name = "node_provider_rewards_api"
path = "src/lib.rs"
