[package]
name = "node-provider-rewards-api"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ic-base-types = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
rewards-calculation = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }

itertools = { workspace = true }
chrono = { version = "0.4.41", default-features = false, features = [
    "alloc",
    "clock",
    "serde",
] }

[lib]
name = "node_provider_rewards_api"
path = "src/lib.rs"
