[package]
name = "decentralization"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { workspace = true }
ahash = { workspace = true }
anyhow = { workspace = true }
ic-base-types = { workspace = true }
ic-management-types = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rand_seeder = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum_macros = { workspace = true }
tabular = { workspace = true }
futures.workspace = true

[dev-dependencies]
tokio = { workspace = true }
regex = { workspace = true }
