[package]
name = "decentralization"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
serde = { version = "1.0", features = ["rc"] }
serde_json = { version = "1.0" }
async-trait = "0.1.52"
actix-web = { version = "4.2.1", default-features = false, features = [
  "compress-gzip",
  "macros",
] }
colored = "2.0.0"
reqwest = { version = "0.11.9", features = ["json"] }
itertools = "0.11.0"
chrono = "0.4.31"
tokio = { version = "1.2.0", features = ["full"] }
ic-management-types = { path = "../ic-management-types" }
futures-util = "0.3.21"
strum = "0.25.0"
strum_macros = "0.25.1"
anyhow = "1.0.44"
log = "0.4.14"
tabular = "0.2"
rayon = "1.5.1"
easy-parallel = "3.1.0"
lru = "0.11.0"
rand = { version = "0.8.5", features = ["std_rng"] }
rand_seeder = "0.2.3"
ahash = "0.8.3"

[dev-dependencies]
include_dir = "0.7.2"
regex = "1.5.4"
