[package]
name = "decentralization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-base-types = { git = "https://github.com/dfinity/ic.git", rev = "36f4a1c2903aed012b95b3b073e052c4036aef09" }
serde = { version = "1.0", features = ["rc"] }
serde_json = { version = "1.0" }
async-trait = "0.1.52"
actix-web = { version = "4.1.0", default-features = false, features = [
  "compress-gzip",
  "macros",
] }
colored = "2.0.0"
reqwest = { version = "0.11.9", features = ["json"] }
counter = "0.5.2"
itertools = "0.10.3"
chrono = "0.4.19"
tokio = { version = "1.2.0", features = ["full"] }
lazy_static = "1.4.0"
ic-management-types = { path = "../ic-management-types" }
futures-util = "0.3.21"
strum = "0.24.1"
strum_macros = "0.24.3"
anyhow = "1.0.44"
log = "0.4.14"
tabular = "0.2"

[dev-dependencies]
include_dir = "0.7.2"
regex = "1.5.4"
