openapi: "3.0.0"
info:
  description: "API Specification for DecentralizationManager backend"
  version: "1.0.0"
  title: "Topology and Release Management API"
  contact:
    name: "Release Team"
    url: "https://app.slack.com/client/T43F9UHS5/C01DB8MQ5M1"

paths:
  /subnets:
    get:
      summary: "Gets the subnet decentralization of a given subnet"
      description: ""
      operationId: "subnet_decentralization"
      parameters:
        - name: id
          in: "query"
          schema:
            type: string
      responses:
        503:
          description: "Catchall"
        200:
          description: "A JSON decentralization score"
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/DecentralizationScore"
          
components:
  schemas:
    DecentralizationScore:
      type: object
      properties:
        scores:
          type: object
          properties:
            city: number
            country: number
            datacenter_owner: number
            node_provider: number
            datacenter: number
            continent: number
        total:
          type:
            number
