[package]
name = "rewards-calculation"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ic-cdk = { workspace = true }
ic-types = { workspace = true }
ic-base-types = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
ic-protobuf = { workspace = true }

[dev-dependencies]
chrono = { version = "0.4.38", default-features = false, features = [
    "alloc",
    "clock",
    "serde",
] }
maplit = "1.0"

[lib]
name = "rewards_calculation"
path = "src/lib.rs"
