#!/usr/bin/env bash
set -euo pipefail
source $(dirname "$0")/lib.sh

if [ $# -lt 1 ]; then
    print_usage
    exit 1
fi

NETWORK=mainnet
OP_NAME=$1
shift
OP_ARGS=$@

IC_ADMIN="${IC_ADMIN:-ic-admin}"
check_ic_admin
check_jq

NNS_URL=${NNS_URL:-'http://[2001:470:1:c76:5000:2cff:fe0c:f490]:8080'}
HSM_PIN_FILE="$HOME/.hsm-pin"
KEY_ID=${HSM_KEY_ID:-$KEY_ID}
check_env_mainnet

DFX_HSM_PIN=$(cat $HSM_PIN_FILE)
AUTH_PARAMS="--use-hsm --slot=$HSM_SLOT --key-id=$KEY_ID --pin=$DFX_HSM_PIN"
check_env_common_for_proposal

maybe_do_operation
