[package]
name = "obs-canister-clients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-agent = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
rand = "0.8"
url = "2.2.2"
