# generated by datamodel-codegen:
#   filename:  release-index-schema.json
from __future__ import annotations

from datetime import date
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import RootModel


class Version(BaseModel):
    """A version of the release."""

    model_config = ConfigDict(extra="forbid")
    version: str
    name: str
    subnets: Optional[List[str]] = None


class Stage(BaseModel):
    """A stage in the rollout."""

    model_config = ConfigDict(extra="forbid")
    subnets: Optional[List[str]] = None
    bake_time: Optional[str] = None
    update_unassigned_nodes: Optional[bool] = None
    wait_for_next_week: Optional[bool] = None


class Release(BaseModel):
    """A release."""

    model_config = ConfigDict(extra="forbid")
    rc_name: str
    versions: List[Version]


class Rollout(BaseModel):
    """A rollout."""

    model_config = ConfigDict(extra="forbid")
    pause: Optional[bool] = None
    skip_days: Optional[List[date]] = None
    stages: List[Stage]


class ReleaseIndex(BaseModel):
    """The release index."""

    model_config = ConfigDict(extra="forbid")
    rollout: Rollout
    releases: List[Release]


class Model(RootModel[ReleaseIndex]):
    """The root model."""

    root: ReleaseIndex
