# generated by datamodel-codegen:
#   filename:  release-index-schema.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Version(BaseModel):
    model_config = ConfigDict(extra='allow')
    name: str
    version: str
    security_fix: Optional[bool] = None


class Release(BaseModel):
    model_config = ConfigDict(extra='forbid')
    rc_name: str
    versions: List[Version]


class ReleaseIndex(BaseModel):
    model_config = ConfigDict(extra='forbid')
    releases: List[Release]


class Model(RootModel[ReleaseIndex]):
    root: ReleaseIndex
