[target.x86_64-unknown-linux-gnu]
linker = "clang"

[alias]
cross-x86 = "zigbuild --bin dre --release --target x86_64-apple-darwin"
cross-aarch = "zigbuild --bin dre --release --target aarch64-apple-darwin"
