[package]
name = "node-status-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
service-discovery ={ path = "../service-discovery" }
clap = { version = "4.3.0", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
anyhow = "1.0.75"
slog = { version = "2.7.0", features = [
  "max_level_trace",
  "nested-values",
  "release_max_level_debug",
  "release_max_level_trace",
] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
humantime = "2.0"
url = "2.2.2"
ic-async-utils = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
futures-util = "0.3.5"
ic-metrics = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
ic-agent = { version = "0.30.2", features = ["hyper"] }
obs-canister-clients = { path = "../obs-canister-clients" }
prometheus-http-query = { version = "0.6.6", default_features = false, features = [
  "rustls-tls-webpki-roots",
] }

[[bin]]
name = "node-status-updater"
path = "src/main.rs"