[package]
name = "sns-downloader"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
crossbeam = { workspace = true }
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
humantime = { workspace = true }
ic-async-utils = { workspace = true }
multiservice-discovery-shared = { path = "../multiservice-discovery-shared" }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
