[package]
name = "log-noise-filter-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
axum = { workspace = true }
slog = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }

[[bin]]
name = "log-noise-filter-backend"
path = "src/main.rs"

[lib]
name = "log_noise_filter_backend"
path = "src/lib.rs"
