[package]
name = "prometheus-config-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
clap = { version = "3.2.25", features = ["derive"] }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
futures-util = "0.3.5"
humantime = "2.0"
ic-async-utils = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-metrics = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-types = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-crypto-utils-threshold-sig-der = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
base64 = { version = "0.13.1" }
regex = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["std"] }
service-discovery = { path = "../service-discovery" }
slog = { version = "2.7.0", features = [
  "max_level_trace",
  "nested-values",
  "release_max_level_debug",
  "release_max_level_trace",
] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tokio = { version = "1.35.1", features = ["full"] }
url = { version = "2.1.1", features = ["serde"] }
config-writer-common = { path = "../config-writer-common" }
ic-config = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
ic-http-endpoints-metrics = { git = "https://github.com/dfinity/ic.git", rev = "4b3b2ce76c4bde0c1c60fb80b0915931003b7eca" }
