name: Update k8s deployments
description: Reusable action for updating k8s deployments

inputs:
  github_api_token:
    description: "A Github API token with access to the k8s repository"
    required: true

runs:
  using: composite
  steps:
    - name: "☸️ Update k8s deployments"
      id: "update_k8s"
      env:
        GITHUB_API_TOKEN: ${{ inputs.github_api_token }}
      shell: bash
      run: |
        set -eExou pipefail

        # List of files can be update in
        # .github/workflows/main.yaml
        echo "Should change following files:"
        echo $files

        cd .git

        # checkout branch
        git clone --depth 10 --branch "main" "https://${GITHUB_API_TOKEN}@github.com/dfinity-ops/k8s.git"

        cd k8s
        git config user.email "idx@dfinity.org"
        git config user.name "IDX Automation"
        DRE_REPO_BRANCH="${{ github.head_ref || github.ref_name }}"
        K8S_REPO_BRANCH="update-dre-images-$DRE_REPO_BRANCH"
        git checkout -b "${K8S_REPO_BRANCH}"

        # Update the internal dashboard image refs
        # this regex matches the first group (ie the image name) and uses \1
        # called a back-reference to insert the first group matched, the second
        # part is to match the 40 characters hash that we replace with the $GITHUB_SHA
        sed -i "s~\(\([[:alpha:]]\|-\)\+\):[[:alnum:]]\{40\}~\1:${GITHUB_SHA}~g" $files

        # commit changes if there are any
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        # Push changes and create a new merge request
        git commit -m "Updating DRE container images from $DRE_REPO_BRANCH branch"
        git push \
          --force --set-upstream origin "${K8S_REPO_BRANCH}" || \
          git push --force --set-upstream origin "${K8S_REPO_BRANCH}"

        (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
        && sudo mkdir -p -m 755 /etc/apt/keyrings \
        && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

        echo "$GITHUB_API_TOKEN" > token.txt
        gh auth login --with-token < token.txt
        gh pr create \
          --body "Updating the DRE container images based on the latest changes in the DRE repository - [here](https://github.com/dfinity/dre/commits/$DRE_REPO_BRANCH)" \
          --title "[nomrbot] - Updating DRE container images" \
          --base "main" \
          --head "$K8S_REPO_BRANCH" \
          --assignee "@me" \
          --reviewer "@dfinity-ops/dre"
