name: Update k8s deployments
description: Reusable action for updating k8s deployments

inputs:
  gitlab_api_token:
    description: 'A GitLab API token with access to the k8s repository'
    required: true
  paths:
    description: 'Paths in k8s repo to update'
    required: true

runs:
  using: composite
  steps:
    - name: "☸️ Update k8s deployments"
      env:
        GITLAB_API_TOKEN: ${{ inputs.gitlab_api_token }}
        K8S_PATHS: ${{ inputs.paths }}
      shell: bash
      run: |
        set -eExou pipefail

        files=$K8S_PATHS
        echo "Should change following files:"
        echo $files

        cd .git

        # checkout branch
        git clone "https://gitlab-ci-token:${GITLAB_API_TOKEN}@gitlab.com/dfinity-lab/private/k8s/k8s.git"

        cd k8s
        git config user.email "idx@dfinity.org"
        git config user.name "IDX Automation"
        git checkout -b "update-image-tag-${GITHUB_SHA}"

        # Update the internal dashboard image refs
        # this regex matches the first group (ie the image name) and uses \1
        # called a back-reference to insert the first group matched, the second
        # part is to match the 40 characters hash that we replace with the $GITHUB_SHA
        sed -i "s~\(\([[:alpha:]]\|-\)\+\):[[:alnum:]]\{40\}~\1:${GITHUB_SHA}~g" ${K8S_PATHS}

        # commit changes if there are any
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        # Push changes and create a new merge request
        git commit -m "Updating container base image refs"
        git push \
          -o merge_request.create \
          -o merge_request.title="[nomrbot] - Updating container image refs mainnet-dashboard [$GITHUB_SHA]" \
          -o merge_request.description="Changes to the release repository - [here](https://github.com/dfinity/dre/commit/$GITHUB_SHA)" \
          --force --set-upstream origin "update-image-tag-${GITHUB_SHA}"
