name: Update k8s deployments
description: Reusable action for updating k8s deployments

inputs:
  push-token:
    description: "The Github token needed to create PRs"
    required: true
  component:
    description: "Which component to update"
    required: true

runs:
  using: composite
  steps:
    - name: Check out k8s repository
      uses: actions/checkout@v4
      with:
        repository: dfinity-ops/k8s
        token: ${{ inputs.push-token }}
        ref: main
        fetch-depth: 10
        path: k8s
    - name: "Create rollout commit with updated container images"
      id: "create-rollout-commit"
      env:
        PUSH_TOKEN: ${{ inputs.push-token }}
        COMPONENT: ${{ inputs.component }}
      shell: bash
      run: |
        set -eExu -o pipefail

        # List of files can be update in
        # .github/workflows/main.yaml
        echo "Should change following files:"
        echo $files
        cd k8s

        git config user.email "idx@dfinity.org"
        git config user.name "IDX Automation"
        SOURCE_BRANCH="${{ github.head_ref || github.ref_name }}"
        K8S_REPO_BRANCH="update-$(basename $GITHUB_REPOSITORY)-$COMPONENT-images-from-$SOURCE_BRANCH"
        git checkout -b "${K8S_REPO_BRANCH}"

        # Update the internal dashboard image refs
        # this regex matches the first group (ie the image name) and uses \1
        # called a back-reference to insert the first group matched, the second
        # part is to match the 40 characters hash that we replace with the $GITHUB_SHA
        prev_commit=$(sed -rn 's~(.*)'"(.*):"'([a-f0-9]{40}).*~\3~p' $files | head -n 1)
        sed -i "s~\(\([[:alpha:]]\|-\)\+\):[[:alnum:]]\{40\}~\1:${GITHUB_SHA}~g" $files

        # commit changes if there are any
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        # Push changes and create a new merge request
        git commit -m "New $COMPONENT release from $SOURCE_BRANCH branch"
        git push \
          --force --set-upstream origin "${K8S_REPO_BRANCH}" || \
          git push --force --set-upstream origin "${K8S_REPO_BRANCH}"

        echo "k8s_branch=$K8S_REPO_BRANCH" >> $GITHUB_OUTPUT
        echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
        echo "previous_ref=$prev_commit" >> $GITHUB_OUTPUT
        echo "current_ref=$GITHUB_SHA" >> $GITHUB_OUTPUT
    - name: "Create PR to roll out with updated container images"
      id: create-rollout-pr
      if: ${{ steps.create-rollout-commit.outputs.k8s_branch != '' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.push-token }}
        script: |
          const owner = 'dfinity-ops';
          const repo = 'k8s';
          const base = 'main';
          const head = '${{ steps.create-rollout-commit.outputs.k8s_branch }}';
          const title = 'Rollout of ${{ inputs.component }} from ${{ github.repository }}@${{ github.head_ref || github.ref_name }}';
          const pulls = await github.rest.pulls.list({
            owner: owner,
            repo: repo,
            base: base,
            state: 'open'
          });
          const pulldata = pulls.data.filter((pull) => pull.title == title);
          if (pulldata.length > 0) {
            console.log("Existing PRs:");
            console.log(pulldata);
            var result = await github.rest.pulls.update({
              owner: owner,
              repo: repo,
              pull_number: pulldata[0].number,
              body: 'Updating container images to incorporate [these changes](https://github.com/${{ github.repository }}/compare/${{ steps.create-rollout-commit.outputs.previous_ref }}..${{ steps.create-rollout-commit.outputs.current_ref }}).',
            });
            console.log("Updated pull request " + pulldata[0].number);
            return result;
          } else {
            var result = await github.rest.pulls.create({
              title: title,
              owner: owner,
              repo: repo,
              head: head,
              base: base,
              maintainer_can_modify: true,
              body: 'Updating container images to incorporate [these changes](https://github.com/${{ github.repository }}/compare/${{ steps.create-rollout-commit.outputs.previous_ref }}..${{ steps.create-rollout-commit.outputs.current_ref }}).'
            });
            console.log("Created pull request:");
            console.log(result);
            return result;
          }
