.bazel:
  stage: build
  image: gcr.io/bazel-public/bazel:6.3.0
  rules:
    - !reference [.rules-default, rules]
  before_script:
    - |-
      mkdir -p ~/.docker
      auth=$(echo -n "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" | base64)
      cat <<EOT > ~/.docker/config.json
      {
        "auths": {
          "${CI_REGISTRY}": {
              "auth": "${auth}"
          }
        }
      }
      EOT

bazel:
  extends:
    - .bazel
  script:
    - &bazel-build-push |
      bazel build --config=ci ...
      bazel test --config=ci ...
      bazel query --noshow_progress 'kind("oci_push", ...)' | xargs -P $(nproc) -I_target bazel run _target -- --tag ${CI_COMMIT_SHA}

bazel-linear-jira:
  extends:
    - .bazel
  script:
    - cd linear-jira
    - *bazel-build-push

factsdb:
  extends:
    - .bazel
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "update-factsdb"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
      allow_failure: true # the pipeline continues running even if the manual job is not run
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: manual
      allow_failure: true # the pipeline continues running even if the manual job is not run
  script:
    - |
      set -exou pipefail  # Don't tolerate any errors
      # Work on main branch
      ls -la
      git config pull.rebase true
      git config --global user.name "Release Team"
      git config --global user.email "eng-release-bots-aaaafbmaump5gpag4pbjfuarry@dfinity.slack.com"
      time git pull --depth 5 --force origin "${CI_DEFAULT_BRANCH}"
      git checkout --force "${CI_DEFAULT_BRANCH}"

      set +x
      time ./bin/factsdb.sh
      if [[ -n "$(git status --short factsdb/data)" ]]; then
        echo "Changed files found";
        git add factsdb/data
        git stash
        git pull --rebase
        git stash pop
        git add factsdb/data
        git status
        git commit -m"Updated FactsDB"
        git remote set-url origin "https://token:${GITLAB_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}"
        git push origin "${CI_DEFAULT_BRANCH}"
      fi
