.bazel:
  stage: build
  image: gcr.io/bazel-public/bazel:6.3.0
  rules:
    - !reference [.rules-default, rules]
  before_script:
    - |-
      mkdir -p ~/.docker
      auth=$(echo -n "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" | base64)
      cat <<EOT > ~/.docker/config.json
      {
        "auths": {
          "${CI_REGISTRY}": {
              "auth": "${auth}"
          }
        }
      }
      EOT

bazel:
  extends:
    - .bazel
  script:
    - &bazel-build-push |
      bazel build --config=ci ...
      bazel test --config=ci ...
      bazel query --noshow_progress 'kind("oci_push", ...)' | xargs -P $(nproc) -I_target bazel run _target -- --tag ${CI_COMMIT_SHA}

bazel-linear-jira:
  extends:
    - .bazel
  script:
    - cd linear-jira
    - *bazel-build-push
