.pre-commit:
  extends:
    - .rules-default
    - .k8s-workers
  interruptible: true
  needs: []
  dependencies: []
  stage: test
  variables:
    PRE_COMMIT_HOME: "/cache/pre-commit/${CI_PROJECT_PATH}/$CI_CONCURRENT_ID"
  script:
    - pre-commit install
    - pre-commit run -a --hook-stage=manual

cargo-clippy:
  extends:
    - .rules-default
    - .k8s-workers
  interruptible: true
  needs: []
  dependencies: []
  stage: test
  script:
    - cd rs
    - ./cargo-clippy

cargo-test:
  extends:
    - .rules-default
    - .k8s-workers
  interruptible: true
  needs: []
  dependencies: []
  stage: test
  script:
    - cd rs
    - cargo test

valid-inventory:
  extends:
    - .rules-default
    - .k8s-workers
  interruptible: true
  needs: []
  dependencies: []
  stage: test
  script:
    - |
      set -exou pipefail  # Don't tolerate any errors
      set +x

      for depl in mainnet mercury staging; do
          if [[ "$depl" == "mainnet" ]]; then ARGS="--decentralized-deployment"; else ARGS=""; fi
          echo "************************************************************"
          echo "Listing Ansible inventory for: $depl"
          echo "************************************************************"
          ./deployments/env/$depl/hosts $ARGS --list > $depl-hosts-list.json
          head $depl-hosts-list.json
          echo "<contents trimmed>"
          echo "word count [wc $depl-hosts-list.json]: $(wc $depl-hosts-list.json)"

          echo "************************************************************"
          echo "Listing nodes for: $depl"
          echo "************************************************************"
          ./deployments/env/$depl/hosts $ARGS --nodes

          echo "************************************************************"
          echo "Listing NNS nodes for: $depl"
          echo "************************************************************"
          ./deployments/env/$depl/hosts $ARGS --nns-nodes
      done
      for depl in dev prod; do
          echo "************************************************************"
          echo "Listing Boundary Nodes Ansible inventory for: $depl"
          echo "************************************************************"
          ./deployments/boundary-nodes/env/$depl/hosts --list > $depl-hosts-list.json
          head $depl-hosts-list.json
          echo "<contents trimmed>"
          echo "word count [wc $depl-hosts-list.json]: $(wc $depl-hosts-list.json)"

          echo "************************************************************"
          echo "Listing Boundary Nodes for: $depl"
          echo "************************************************************"
          ./deployments/boundary-nodes/env/$depl/hosts --nodes
      done
