.pre-commit:
  extends:
    - .rules-default
    - .k8s-workers
  interruptible: true
  needs: []
  dependencies: []
  stage: test
  variables:
    PRE_COMMIT_HOME: "/cache/pre-commit/${CI_PROJECT_PATH}/$CI_CONCURRENT_ID"
  script:
    - pre-commit install
    - pre-commit run -a --hook-stage=manual
