[package]
name = "node-provider-rewards"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ic-types = { workspace = true }
ic-base-types = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
ic-management-canister-types = { workspace = true }
tabled = { workspace = true }
tabular = { workspace = true }
chrono = { workspace = true }
function_name = "0.3"

[dev-dependencies]
maplit = "1.0.2"

[lib]
name = "node_provider_rewards"
path = "src/lib.rs"
