name: Build and push runner image

on:
  push:
    branches:
      - "main"
    paths:
      - "docker/runner.Dockerfile"
      - "docker/runner.Dockerfile.dockerignore"
      - ".github/workflows/build-runner.yaml"
  pull_request:
    paths:
      - "docker/runner.Dockerfile"
      - "docker/runner.Dockerfile.dockerignore"
      - ".github/workflows/build-runner.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Build and push runner image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "🔧 Login to GitHub Container Registry"
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Copy docker image dependencies"
        run: cp pyproject.toml requirements.lock requirements-dev.lock .python-version README.md rust-toolchain.toml docker/
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: ./docker
          file: ./docker/runner.Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/dfinity/dre/actions-runner:${{ github.sha }}
