name: Build and push linear-jira image
on:
  push:
    paths:
      - linear-jira/**
      - ./.github/workflows/linear-jira.yaml
    # branches:
    #   - "*"
  pull_request:
    paths:
      - linear-jira/**
      - ./.github/workflows/linear-jira.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "🚀 Building"
        run: |
          cd linear-jira; bazel build --config=ci ...

      - name:  "🔧 Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "📦 Push images to GitHub Container Registry"
        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
        run: cd linear-jira; bazel query --noshow_progress 'kind("oci_push", ...)' | xargs -I_target bazel run _target -- --tag ${GITHUB_SHA}
