name: MSD Diff

on:
  pull_request:
    paths:
      - 'rs/ic-observability/multiservice-discovery*/src/**'

jobs:
  setup-runner:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: "🔧 Setup runner"
        uses: ./.github/workflows/manage-runner-pre

      - name: "Download main test artifact"
        uses: dawidd6/action-download-artifact@v3.0.0
        with:
          name: test-artifacts
          branch: main

      - name: "Compute MSD"
        run: |
          set -exuo pipefail
          mkdir -p /home/runner/work/tmp
          ./test-artifacts -- --targets-dir /home/runner/work/tmp/registry --destination-targets /home/runner/work/main-targets
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir /home/runner/work/tmp/registry --destination-targets /home/runner/work/branch-targets

      - uses: "int128/diff-action@v1"
        name: Check MSD Diff
        with:
          base: /home/runner/work/main-targets
          head: /home/runner/work/branch-targets
