name: multiservice-discovery diff

on:
  pull_request:
    paths:
      - 'rs/ic-observability/multiservice-discovery/src/*'
    types:
      - opened
      - synchronize

jobs:
  observability-check:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        branch: [main, ${{ github.event.pull_request.head.ref }}]

    steps:
      - uses: actions/checkout@v4
      - name: "🔧 Setup runner"
        uses: ./.github/workflows/manage-runner-pre
      - name: Build and Run on Current Branch
        run: |
          bazel build //rs/ic-observability/multiservice-discovery/src:your_bazel_target
          bazel-bin/rs/ic-observability/multiservice-discovery/src/your_bazel_target \
          && curl -sSf http://localhost > result_new

      - name: Checkout main branch
        run: |
          git fetch
          git checkout origin/main -b main

      - name: Build and Run on Main Branch
        run: |
          bazel build //rs/ic-observability/multiservice-discovery/src:your_bazel_target
          bazel-bin/rs/ic-observability/multiservice-discovery/src/your_bazel_target \
          && curl -sSf http://localhost > result_main

      - name: Compare Results and Comment on PR
        run: |
          diff_result=$(diff -u result_main result_new) || true
          if [ -n "$diff_result" ]; then
            echo "Differences found. Commenting on the PR."
            echo "$diff_result" | tee comment.txt
            curl -XPOST -sSf -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"\`diff\n$(cat comment.txt)\n\`\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          else
            echo "No differences found."
          fi