name: MSD diff

on:
  push:
    branches:
      - add-multiservice-discovery-diff
  pull_request:
    paths:
      - 'rs/ic-observability/multiservice-discovery/src/*'
    types:
      - opened
      - synchronize

jobs:
  compute-msd:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branch: [branch, main]
    steps:
      - name: Branch Check
        id: branch-check
        run: |
          if [ ${{ matrix.branch }} -eq "branch" ]; then
              BRANCH=${{ github.event.pull_request.head.ref }}
          else
              BRANCH=main
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-check.outputs.branch }}

      - name: "🔧 Setup runner"
        uses: ./.github/workflows/manage-runner-pre

      - name: Compute MSD
        id: msd
        run: |
          set -exuo pipefail
          RESULT_DIR=/home/runner/work/targets-${{ steps.branch-check.outputs.branch }}
          mkdir -p $RESULT_DIR
          mkdir -p /home/runner/work/tmp
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir /home/runner/work/tmp &
          pid=$!
          url="http://localhost:8000/prom/targets"
          max_retries=500
          retry_interval=5
          retry_count=0
          while true; do
              http_status=$(curl -s -o /dev/null -w "%{http_code}" "$url" || true)
              if [ "$http_status" -eq 200 ]; then
                  break
              else
                  retry_count=$((retry_count + 1))
                  sleep $retry_interval

                  if [ $retry_count -eq $max_retries ]; then
                      break
                  fi
              fi
          done
          curl -sL http://localhost:8000/prom/targets > $RESULT_DIR/targets.json
          kill $pid
          echo "result_dir=$RESULT_DIR" >> $GITHUB_OUTPUT

  Diff:
    runs-on: ubuntu-20.04
    steps:
      - uses: int128/diff-action@v1
        name: Check MSD Diff
        with:
          base: /home/runner/work/targets-main
          head: /home/runner/work/targets-${{ github.event.pull_request.head.ref }}
