name: multiservice-discovery diff

on:
  push:
    branches:
      - add-multiservice-discovery-diff
# on:
#   pull_request:
#     paths:
#       - 'rs/ic-observability/multiservice-discovery/src/*'
#     types:
#       - opened
#       - synchronize

jobs:
  compute-targets-diff:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "🔧 Setup runner"
        uses: ./.github/workflows/manage-runner-pre

      - name: branch-run
        id: branch-run
        run: |
          mkdir /branch-result
          mkdir /discovery_wd
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir /discovery_wd
          until curl -sSf -o /dev/null http://localhost; do
          sleep 5
          elapsed=$((elapsed + 5))
          if [ $elapsed -ge 300 ]; then
            echo "Timeout reached. Exiting."
            exit 1
          fi
          done
          curl -sSf http://localhost > "/branch-result/targets.json"

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: main run
        id: main-run
        run: |
          mkdir /main-result
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir /discovery_wd
          until curl -sSf -o /dev/null http://localhost; do
          sleep 5
          elapsed=$((elapsed + 5))
          if [ $elapsed -ge 300 ]; then
            echo "Timeout reached. Exiting."
            exit 1
          fi
          done
          bazel-bin/rs/ic-observability/multiservice-discovery/src/your_bazel_target \
          && curl -sSf http://localhost > "/main-result/targets.json"

      - uses: int128/diff-action@v1
        with:
          base: ${{ steps.main-run.outputs.directory }}
          head: ${{ steps.branch-run.outputs.directory }}
