name: MSD Diff
on:
  pull_request:
    paths:
      - 'rs/ic-observability/multiservice-discovery*/src/**'
jobs:
  setup-runner:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: "Download main test artifact"
        uses: dawidd6/action-download-artifact@v3.0.0
        with:
          search_artifacts: true
      - name: "🔧 Setup runner"
        uses: ./.github/workflows/manage-runner-pre

      - name: "Compute MSD"
        run: |
          set -exuo pipefail
          ./test-artifacts -- --targets-dir . > /home/runner/work/main-targets
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir . > /home/runner/work/branch-targets

      - uses: "int128/diff-action@v1"
        name: Check MSD Diff
        with:
          base: main-targets
          head: branch-targets
