name: MSD Diff
on:
  pull_request:
    paths:
      - 'rs/ic-observability/multiservice-discovery*/src/**'
jobs:
  setup-runner:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: "Download main test artifact"
        uses: dawidd6/action-download-artifact@v3.0.0
        with:
          name: test-artifacts
          branch: main
          workflow: main.yaml

      - name: "Compute MSD"
        run: |
          set -exuo pipefail
          mkdir -p tmp/registry main-targets branch-targets
          chmod +x multiservice-discovery
          ./multiservice-discovery --targets-dir tmp/registry --render-prom-targets-to-stdout > main-targets/targets.json
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir tmp/registry --render-prom-targets-to-stdout > branch-targets/targets.json

      - name: Check MSD Diff
        uses: "int128/diff-action@v1"
        with:
          base: main-targets
          head: branch-targets
