name: Auto update PR's
on:
  push:
    branches:
      - main-disabled  # change back to "main" to re-enable

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}
      - uses: chinthakagodawita/autoupdate@v1.7.0
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "1000"
          MERGE_CONFLICT_ACTION: "ignore"
