name: Pull request update

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update all pull requests
        uses: castastrophe/actions-pr-auto-update@v1.1.0
        with:
          # defaults to github.token
          token: ${{ secrets.GIX_CREATE_PR_PAT }}
          include_drafts: true
