name: Release

on:
  pull_request:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed release files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            release-index.yaml
            replica-releases/**

      - name: Mark bazel as success # because it should not run if only release files changed
        uses: Sibz/github-status-action@v1
        if: ${{ steps.changed-files.outputs.all_changed_files_count > 0 && steps.changed-files.outputs.other_changed_files_count == 0  }}
        with:
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'bazel'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
