name: Release

on:
  pull_request:
  workflow_dispatch:

jobs:
  changed_files:
    runs-on:
      labels: dre-runner-custom
    # This image is based on ubuntu:20.04
    container: ghcr.io/dfinity/dre/actions-runner:f47914030bbdb5c3d542aa876ba8a11a6b183bff
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed release files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            release-index.yaml
            replica-releases/**
            node-labels/**
            facts-db/**

      - name: Mark bazel as success # because it should not run if only release files changed
        uses: Sibz/github-status-action@v1
        if: ${{ steps.changed-files.outputs.all_changed_files_count > 0 && steps.changed-files.outputs.other_changed_files_count == 0  }}
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "bazel"
          description: "Passed"
          state: "success"
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Run checks for release index
        run: |
          rye sync
          rye run python3 release-controller/ci_check.py --repo-path /home/runner/.cache
