name: Release index checks

on:
  pull_request:
    paths:
      - "release-index.yaml"
      - "replica-releases/**"
      - "release-controller/**"
      - "node-labels/**"
      - "facts-db/**"
      - .github/**
  workflow_dispatch:

jobs:
  changed_files:
    runs-on:
      labels: dind-small
    # This image is based on ubuntu:20.04
    container: ghcr.io/dfinity/dre/actions-runner:6413f2909a49329ecbf5371ee7ddf07a9799b625
    name: Check changed release index files
    steps:
      - uses: actions/checkout@v4
      - name: Run checks for release index
        run: |
          rye sync
          export PYTHONPATH=$PWD/release-controller
          rye run python3 scripts/release_index_ci_check.py --repo-path /home/runner/.cache
