name: Release

on:
  pull_request:

jobs:
  changed_files:
    runs-on:
      labels: dre-runner-custom
    # This image is based on ubuntu:20.04
    container: ghcr.io/dfinity/dre/actions-runner:9994667f9257350d20c17f8bcbb2d7b3392f39b9
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed release files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            release-index.yaml
            replica-releases/**
            node-labels/**

      - name: Mark bazel as success # because it should not run if only release files changed
        uses: Sibz/github-status-action@v1
        if: ${{ steps.changed-files.outputs.all_changed_files_count > 0 && steps.changed-files.outputs.other_changed_files_count == 0  }}
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'bazel'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Run checks for release index
        if: ${{ steps.changed-files.outputs.all_changed_files_count > 0 && steps.changed-files.outputs.other_changed_files_count == 0  }}
        run: |
          python release-controller/ci_check.py --repo-path /home/runner/.cache
