name: Required checks
on:
  push: {}
  workflow_run:
    workflows:
      - Release controller
      - Build and test

concurrency:
  group: ${{ github.workflow }}-required-checks-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  wait-for-other-jobs:
    name: Wait for required jobs to complete or be skipped
    runs-on: ubuntu-latest
    steps:
      - name: Wait for running jobs
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          running-workflow-name: Wait for required jobs to complete or be skipped
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          wait-interval: 5
