name: Required checks
on:
  push: {}

concurrency:
  group: ${{ github.workflow }}-required-checks-${{ github.event.push.after || github.ref }}
  cancel-in-progress: true

jobs:
  wait-for-other-jobs:
    name: Wait for required jobs to complete or be skipped
    runs-on: ubuntu-latest
    steps:
      - name: Wait for running jobs
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: Wait for required jobs to complete or be skipped
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          wait-interval: 5
