name: PR Checksum Comparison

on:
  push:
    branches:
      - "test-changes-app"

jobs:
  pr-check:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
          large-packages: false  # this is slow
      - uses: actions/checkout@v4
      - name: Retrieve commit associated with the latest tag in main
        run: |
          set -eExuo pipefail
          git pull
          LATEST_TAG_COMMIT=$(git show-ref --tags -d | sort -k2,2 | tail -n 1 | awk '{print $1}')
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          MANIFEST=$(curl -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/v2/${{ github.repository }}/multiservice-discovery/manifests/$LATEST_TAG_COMMIT)
          echo $MANIFEST
