name: PR Checksum Comparison

on:
  push:
    branches:
      - "test-changes-app"

jobs:
  pr-check:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
          large-packages: false  # this is slow
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Package Digest
        run: |
          DIGEST=$(docker inspect --format '{{index .RepoDigests 0}}' ghcr.io/dre/multiservice-discovery:01428695110934b70d9c1e4af5fa52276b99515a)
          echo "Package Digest: $DIGEST"