name: Daily mainnet-registry update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup runner
        uses: ./.github/workflows/manage-runner-pre
      - name: Update registry
        run: |
          mkdir /mainnet-registry
          bazel run //rs/ic-observability/multiservice-discovery -- --targets-dir /mainnet-registry
          sleep 30
      - name: Update file in another branch
        run: |
          git checkout -b ic-registry-mainnet
          cp /rs/ic-observability/multiservice-discovery/tests/test_data/BUILD /mainnet-registry
          echo "$(date)" > updated-file.txt  # Update this line to modify your file
          git add updated-file.txt
          git commit -m "Update file $(date)"
          git push origin update-branch
